package com.nus.folio.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

val LoginBackground = Color(0xFFFCF6E9)
val LoginBorder = Color(0xFFD0BB9E)
val LoginPrimary = Color(0xFF001F1B)
val LoginCopper = Color(0xFF96541B)
val LoginTextPrimary = Color(0xFF1A1A1A)
val LoginTextSecondary = Color(0xFF6F624D)
val LoginTextMuted = Color(0xFF9E9E9E)
val LoginPlaceholder = Color(0xFFBDBDBD)
val LoginCheckbox = Color(0xFF8E99A4)
val LoginButtonGlow = Color(0xFF2A4A4A)

val HomeHeader = Color(0xFF0B2A24)
val HomeBackground = Color(0xFFF7F1E6)
val HomeSearchField = Color(0xFF163B34)
val HomeSearchPlaceholder = Color(0xFF8FA9A2)
val HomeCardBackground = Color(0xFFFFFBF5)
val HomeCardBorder = Color(0xFFE6DCCB)
val HomeTypeBadgeBackground = Color(0xFFF0E6D6)
val HomeChipSelected = Color(0xFFEDE4D4)
val HomeChipBorder = Color(0xFFD9CEBC)
val HomeTextPrimary = Color(0xFF1A1A1A)
val HomeTextSecondary = Color(0xFF7A7164)
val HomeNavAccent = Color(0xFFC4A35A)
val HomeStatusReadyBackground = Color(0xFFDCEFDA)
val HomeStatusReadyText = Color(0xFF2F6B3A)
val HomeStatusProcessingBackground = Color(0xFFF8E6C8)
val HomeStatusProcessingText = Color(0xFFA86B1E)
val HomeStatusFailedBackground = Color(0xFFF6D6D4)
val HomeStatusFailedText = Color(0xFFA13A34)
val HomeSheetBackground = Color(0xFFFFFBF5)
val HomeSheetHandle = Color(0xFFD9CEBC)
val HomeUploadDash = Color(0xFFD4C7B0)
val HomeUploadIcon = Color(0xFF4A433A)


val AccountBackground = Color(0xFFF7F1E6)
val AccountTitleMuted = Color(0xFFD9CEBC)
val AccountSubtitle = Color(0xFF3D3429)
val AccountAvatar = Color(0xFF9A6B3F)
val AccountCardBackground = Color(0xFFFFFBF5)
val AccountCardBorder = Color(0xFFE6DCCB)
val AccountTextPrimary = Color(0xFF1A1A1A)
val AccountTextSecondary = Color(0xFF9A8B74)
